version: '3.3'

services:
    calendardb:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: OSM_DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: school123
            MYSQL_ROOT_HOST: 127.0.0.1
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes: 
            - ./mysql/calendar/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    classesdb:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: OSM_DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: school123
            MYSQL_ROOT_HOST: 127.0.0.1
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        volumes: 
            - ./mysql/classes/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    contactsdb:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: OSM_DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: school123
            MYSQL_ROOT_HOST: 127.0.0.1
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3308:3306
        volumes: 
            - ./mysql/contacts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    userdb:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: OSM_DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: school123
            MYSQL_ROOT_HOST: 127.0.0.1
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3309:3306
        volumes: 
            - ./mysql/user/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d


    rabbitmq:
        image: rabbitmq:3.7.5-management
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: rmq
            RABBITMQ_DEFAULT_PASS: pass
        ports:
        - 15672:15672
        - 5672:5672
        volumes:
        - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    
    redis:
        image: redis:latest
        restart: always
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
        - 6379:6379


    portainer:
        image: portainer/portainer
        ports:
            - "9000:9000"
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

volumes:
    portainer_data:

