GRANT ALL PRIVILEGES ON *.* to 'dbuser'@'%';

CREATE DATABASE OSM_CALENDAR;
CREATE DATABASE OSM_CONTACTS;
CREATE DATABASE OSM_USER;
CREATE DATABASE OSM_CLASS;

CREATE USER 'dbu_calendar'@'%' IDENTIFIED BY 'school123';
CREATE USER 'dbu_contacts'@'%' IDENTIFIED BY 'school123';
CREATE USER 'dbu_user'@'%' IDENTIFIED BY 'school123';
CREATE USER 'dbu_class'@'%' IDENTIFIED BY 'school123';
GRANT ALL PRIVILEGES ON OSM_CALENDAR.* TO 'dbu_calendar'@'%';
GRANT ALL PRIVILEGES ON OSM_CONTACTS.* TO 'dbu_contacts'@'%';
GRANT ALL PRIVILEGES ON OSM_USER.* TO 'dbu_user'@'%';
GRANT ALL PRIVILEGES ON OSM_CLASS.* TO 'dbu_class'@'%;'